djangoproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('genre/', include('genre.urls')),
    path('admin/', admin.site.urls),
]

genre/urls.py
from django.urls import path
from .import views


urlpatterns = [
    #/genre/
    path('',views.index.as_view(),name='index'),

    #/genre/1(1 represents the id of the collection chosen by the user)
    path('<pk>/',views.details.as_view(),name='details'),

    path('register/',views.UserFormView.as_view(),name='userform'),
]

genre/models.py
from django.db import models

class Collection(models.Model):
    collection_id = models.AutoField(primary_key=True)
    collection_name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    collcover = models.CharField(max_length=1000)

    def __str__(self):
        return self.collection_name

class Piece(models.Model):
    collection = models.ForeignKey(Collection, default=1, on_delete=models.SET_DEFAULT)
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    year = models.IntegerField()
    piececover = models.CharField(max_length=1000)

    def __str__(self):
        return self.title
    
# Create your models here.

genre/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields= ['username','email','password']

genre/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Collection, Piece
from django.views import generic
from .forms import UserForm
from django.contrib.auth import authenticate,login
from django.views.generic import View
# Create your views here.

class index(generic.ListView):
    template_name = "genre/genretemplate.html"

    def get_queryset(self):
        return Collection.objects.all()

class details(generic.DetailView):
    model=Collection
    template_name = "genre/detailtemplate.html"

class UserFormView(django.views.generic.View):
    form_class=UserForm
    template_name='genre/formtemplate.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request=request, template_name='genre/formtemplate.html', context={'form': form})

    def post(self,request):
        form=self.form_class(request.POST)

        if form.is_valid():
            user=form.save()
            username=form.cleaned_data('username')
            password=form.cleaned_data('password')
            user.set_password(password)
            user.save()

            newuser=authenticate(username=username,password=password)

            if newuser is not None:
                if newuser.is_active:
                    login(request,newuser)
                    return redirect("/genre")
        return render(request=request, template_name='genre/formtemplate.html', context={'form': form})

genre/templates/genre/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
               <a class="navbar-brand" href="/genre">Home</a>
            </div>

            <u1 class="nav navbar-nav navbar-right">
                <l1 class="">
                    <a href="/genre/register">
                        Register
                    </a>
                </l1>
                <l1 class="">
                    <a>{{request.user}}</a>
                </l1>
            </u1>
        </div>
    </nav>

{% block content %}
{%endblock%}

</body>
</html>

genre/templates/genre/detailtemplate.html
<!DOCTYPE html>
{%extends 'genre/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Piece</title>
</head>
<body>
{% block content %}
        {% for pieceobj in collection.piece_set.all %}
          <div align="center">
            <img src="{{pieceobj.piececover}}" height="200" width="200">
            <h2>{{pieceobj.title}}-{{pieceobj.artist}}</h2>
            <h3>{{pieceobj.type}}</h3>
            <h3>{{pieceobj.year}}</h3>
            <br/>
          </div>
        {% endfor %}
{%endblock%}

</body>
</html>

genre/templates/genre/formtemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    {%extends 'genre/base.html' %}
</head>
<body>
    {% block content %}
        <form action="" method="post">
            {csrf _token}
            username:
            <input type="text" name="username">
            <br/>

            Email:
            <input type="text" name="email">
            <br/>

            Password:
            <input type="password" name="password">
            <br/>

            <input type="submit" name="submit">

        </form>
    {%endblock%}

</body>
</html>

genre/templates/genre/genretemplate.html
<!DOCTYPE html>
{%extends 'genre/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genre</title>
</head>
<body>
{% block content %}
        {% for genreobj in object_list %}
          <div align="center">
            <img src="{{genreobj.collcover}}" height="200" width="200">
            <h2><a href="/genre/{{genreobj.id}}/">{{genreobj.collection_name}}</a></h2>
            <h3>{{genreobj.description}}</h3>
            <br/>
          </div>
        {% endfor %}
{%endblock%}
</body>
</html>